//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountbalance
    {
        public int year { get; set; }
        public int month { get; set; }
        public Nullable<double> rnd { get; set; }
        public Nullable<double> canteen { get; set; }
        public Nullable<double> ceocar { get; set; }
        public Nullable<double> marketing { get; set; }
        public Nullable<double> parking { get; set; }
        public Nullable<int> uid { get; set; }
    
        public virtual user user { get; set; }
    }
}
